test CIz

diff --git a/.github/workflows/ci-dev.yml b/.github/workflows/ci-dev.yml
--- a/.github/workflows/ci-dev.yml
+++ b/.github/workflows/ci-dev.yml
@@ -41,3 +41,64 @@ jobs:
       - name: Push Docker image
         run: |
           docker push ghcr.io/visiobook-esp/repo-test-infra-dev:latest
+    
+  minikube:
+    name: 🏗️ Deploy & Test ALL Charts on Minikube
+    runs-on: ubuntu-latest
+    needs: docker-build-and-push
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Install kubectl
+        run: |
+          KUBECTL_VERSION="v1.30.1"
+          curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
+          chmod +x kubectl
+          sudo mv kubectl /usr/local/bin/kubectl
+
+      - name: Setup Minikube
+        uses: medyagh/setup-minikube@latest
+        with:
+          kubernetes-version: v1.30.1
+
+      - name: Set up Helm
+        uses: azure/setup-helm@v3
+        with:
+          version: v3.14.0
+      - name: Pull Charts from Infra Repo
+        run : |
+          git clone https://github.com/VisioBook-ESP/infra-helm-charts.git
+          pwd
+          ls -la infra-helm-charts/environnement/dev/charts
+
+#      - name: Deploy & test all charts
+#        run: |
+#          set -e
+#          for chart in environnement/dev/charts/*; do
+#            if [ -f "$chart/Chart.yaml" ]; then
+#              release=$(basename $chart)
+#              echo "🚀 Deploying chart: $release"
+#
+#
+#              helm upgrade --install $release $chart --wait --timeout 180s || {
+#                echo "❌ Helm install failed for $release"
+#                exit 1
+#              }
+#
+#              echo "✅ Chart $release deployed"
+#
+#              svc=$(kubectl get svc -l "app.kubernetes.io/instance=$release" -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true)
+#
+#              if [ -n "$svc" ]; then
+#                echo "🔍 Service found for $release: $svc"
+#
+#                nohup kubectl port-forward svc/$svc 8080:80 >/dev/null 2>&1 &
+#                sleep 5
+#                echo "🌐 Testing service for $release"
+#                curl --max-time 10 --retry 5 --retry-delay 5 http://127.0.0.1:8080 || echo "⚠️ Curl failed for $release"
+#                kill $(jobs -p) || true
+#              else
+#                echo "⚠️ No service found for $release, skipping curl test"
+#              fi
+#            fi
+#          done
